[HighlighterSetCollection]
version=2
active_sets=@Invalid()
sets\1\HighlighterSet\version=3
sets\1\HighlighterSet\name=iOS Logs (Modern Elements)
sets\1\HighlighterSet\id=pleasant123456789012345678901234
sets\1\HighlighterSet\highlighters\1\regexp=^[A-Z][a-z]{2}\\s+\\d+\\s\\d{2}:\\d{2}:\\d{2}
sets\1\HighlighterSet\highlighters\1\ignore_case=false
sets\1\HighlighterSet\highlighters\1\match_only=true
sets\1\HighlighterSet\highlighters\1\use_regex=true
sets\1\HighlighterSet\highlighters\1\variate_colors=false
sets\1\HighlighterSet\highlighters\1\color_variance=15
sets\1\HighlighterSet\highlighters\1\fore_colour=#ff888888
sets\1\HighlighterSet\highlighters\1\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\2\regexp=(?<=\\d{2}:\\d{2}:\\d{2}\\s)\\S+
sets\1\HighlighterSet\highlighters\2\ignore_case=false
sets\1\HighlighterSet\highlighters\2\match_only=true
sets\1\HighlighterSet\highlighters\2\use_regex=true
sets\1\HighlighterSet\highlighters\2\variate_colors=false
sets\1\HighlighterSet\highlighters\2\color_variance=15
sets\1\HighlighterSet\highlighters\2\fore_colour=#ff26a69a
sets\1\HighlighterSet\highlighters\2\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\3\regexp=[a-zA-Z0-9_\\-\\.]+(?:\\([^)]+\\))?(?=\\[\\d+\\])
sets\1\HighlighterSet\highlighters\3\ignore_case=false
sets\1\HighlighterSet\highlighters\3\match_only=true
sets\1\HighlighterSet\highlighters\3\use_regex=true
sets\1\HighlighterSet\highlighters\3\variate_colors=false
sets\1\HighlighterSet\highlighters\3\color_variance=15
sets\1\HighlighterSet\highlighters\3\fore_colour=#ffba68c8
sets\1\HighlighterSet\highlighters\3\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\4\regexp=\\[\\d+\\]
sets\1\HighlighterSet\highlighters\4\ignore_case=false
sets\1\HighlighterSet\highlighters\4\match_only=true
sets\1\HighlighterSet\highlighters\4\use_regex=true
sets\1\HighlighterSet\highlighters\4\variate_colors=false
sets\1\HighlighterSet\highlighters\4\color_variance=15
sets\1\HighlighterSet\highlighters\4\fore_colour=#ff5c6bc0
sets\1\HighlighterSet\highlighters\4\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\5\regexp=<(?i)(error|fault|fatal|panic|critical)>
sets\1\HighlighterSet\highlighters\5\ignore_case=true
sets\1\HighlighterSet\highlighters\5\match_only=true
sets\1\HighlighterSet\highlighters\5\use_regex=true
sets\1\HighlighterSet\highlighters\5\variate_colors=false
sets\1\HighlighterSet\highlighters\5\color_variance=15
sets\1\HighlighterSet\highlighters\5\fore_colour=#ffef5350
sets\1\HighlighterSet\highlighters\5\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\6\regexp=<(?i)(warning|warn)>
sets\1\HighlighterSet\highlighters\6\ignore_case=true
sets\1\HighlighterSet\highlighters\6\match_only=true
sets\1\HighlighterSet\highlighters\6\use_regex=true
sets\1\HighlighterSet\highlighters\6\variate_colors=false
sets\1\HighlighterSet\highlighters\6\color_variance=15
sets\1\HighlighterSet\highlighters\6\fore_colour=#ffffa726
sets\1\HighlighterSet\highlighters\6\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\7\regexp=<(?i)(notice|info|debug)>
sets\1\HighlighterSet\highlighters\7\ignore_case=true
sets\1\HighlighterSet\highlighters\7\match_only=true
sets\1\HighlighterSet\highlighters\7\use_regex=true
sets\1\HighlighterSet\highlighters\7\variate_colors=false
sets\1\HighlighterSet\highlighters\7\color_variance=15
sets\1\HighlighterSet\highlighters\7\fore_colour=#ff29b6f6
sets\1\HighlighterSet\highlighters\7\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\8\regexp=\\b0x[a-fA-F0-9]+\\b
sets\1\HighlighterSet\highlighters\8\ignore_case=true
sets\1\HighlighterSet\highlighters\8\match_only=true
sets\1\HighlighterSet\highlighters\8\use_regex=true
sets\1\HighlighterSet\highlighters\8\variate_colors=false
sets\1\HighlighterSet\highlighters\8\color_variance=15
sets\1\HighlighterSet\highlighters\8\fore_colour=#ff66bb6a
sets\1\HighlighterSet\highlighters\8\back_colour=#00ffffff
sets\1\HighlighterSet\highlighters\size=8
sets\size=1
quick\size=0